### ISSUE TITLE
About Upload img

### ISSUE THREAD

**Issue by Phantom-KNA** [supabase-community/supabase-csharp#58]
# Bug report
**Supabase.Storage.BadRequestException:** 'Exception of type 'Supabase.Storage.BadRequestException' was thrown.'
## Describe the bug
**Supabase.Storage.BadRequestException
  Mensaje = Exception of type 'Supabase.Storage.BadRequestException' was thrown.
  Origen = Storage
  Seguimiento de la pila:
   at Supabase.Storage.Helpers.<MakeRequest>d__0`1[[Supabase.Storage.Bucket, Storage, Version=1.2.7.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at Supabase.Storage.StorageBucketApi.CreateBucket(String id, BucketUpsertOptions options)
   at Control_de_Remesas.Views.Employeer.NewEmployeer.CreatedEmBTN_Clicked(Object sender, EventArgs e) in D:\Development\Control de Remesas\Control de Remesas\Views\Employeer\NewEmployeer.xaml.cs:line 35
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:line 36
   at Java.Lang.Thread.RunnableImplementor.Run() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:line 36
   at Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Java.Lang.IRunnable.cs:line 84
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V(_JniMarshal_PP_V callback, IntPtr jnienv, IntPtr klazz) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:line 22

I dont know, not working. I try in C# console app and MAUI app.

**Comment by Phantom-KNA** [comment]
Well, after trying several times, I included insert role in the bucket and it worked. Pls delete this issue
